title: "邓磊的编程博客"
description: "分享我的代码、技巧、经验和思考，记录我的成长和进步。同时希望能帮助其他开发人员提高工作效率。"
url: "https://denglei1024.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-include-cache
  # - jemoji   # 如需要 GitHub emoji 支持
