# Plugins (previously gems:)
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-feed
  - jekyll-include-cache